# dotshot config file

repo_root: "/data/projects"
dotfiles:
  nvim:
    paths:
      - ~/.config/nvim

  ghostty:
    paths:
      - ~/.config/ghostty
  wezterm:
    paths:
      - ~/.config/wezterm
  zsh:
    paths:
      - ~/.zshrc
      - ~/.zshrc.d/
  bash:
    paths:
      - ~/.bashrc
        ~/.bash_profile
git:
  auto_commit: true
  commit_message: "dotshot: sync update"
